import pathlib

DATA_PATH = pathlib.Path(__file__).parent.absolute() / "data"


def get_path(filename):
    return DATA_PATH / filename


RETURN_VALUE_1 = {
    "response": {
        "warnings": [
            {
                "warning": "incomplete return",
                "description": "The API can only return 5000 rows in JSON format.  Please consider constraining your request with facet, start, or end, or using offset to paginate results.",
            }
        ],
        "total": 24,
        "dateFormat": 'YYYY-MM-DD"T"HH24',
        "frequency": "hourly",
        "data": [
            {
                "period": "2023-01-01T00",
                "respondent": "AECI",
                "respondent-name": "Associated Electric Cooperative, Inc.",
                "fueltype": "COL",
                "type-name": "Coal",
                "value": 1956,
                "value-units": "megawatthours",
            },
            {
                "period": "2023-01-01T01",
                "respondent": "AECI",
                "respondent-name": "Associated Electric Cooperative, Inc.",
                "fueltype": "COL",
                "type-name": "Coal",
                "value": 1990,
                "value-units": "megawatthours",
            },
            {
                "period": "2023-01-01T02",
                "respondent": "AECI",
                "respondent-name": "Associated Electric Cooperative, Inc.",
                "fueltype": "COL",
                "type-name": "Coal",
                "value": 1962,
                "value-units": "megawatthours",
            },
            {
                "period": "2023-01-01T03",
                "respondent": "AECI",
                "respondent-name": "Associated Electric Cooperative, Inc.",
                "fueltype": "COL",
                "type-name": "Coal",
                "value": 1928,
                "value-units": "megawatthours",
            },
            {
                "period": "2023-01-01T04",
                "respondent": "AECI",
                "respondent-name": "Associated Electric Cooperative, Inc.",
                "fueltype": "COL",
                "type-name": "Coal",
                "value": 2015,
                "value-units": "megawatthours",
            },
            {
                "period": "2023-01-01T05",
                "respondent": "AECI",
                "respondent-name": "Associated Electric Cooperative, Inc.",
                "fueltype": "COL",
                "type-name": "Coal",
                "value": 2005,
                "value-units": "megawatthours",
            },
            {
                "period": "2023-01-01T06",
                "respondent": "AECI",
                "respondent-name": "Associated Electric Cooperative, Inc.",
                "fueltype": "COL",
                "type-name": "Coal",
                "value": 1888,
                "value-units": "megawatthours",
            },
            {
                "period": "2023-01-01T07",
                "respondent": "AECI",
                "respondent-name": "Associated Electric Cooperative, Inc.",
                "fueltype": "COL",
                "type-name": "Coal",
                "value": 1654,
                "value-units": "megawatthours",
            },
            {
                "period": "2023-01-01T08",
                "respondent": "AECI",
                "respondent-name": "Associated Electric Cooperative, Inc.",
                "fueltype": "COL",
                "type-name": "Coal",
                "value": 1644,
                "value-units": "megawatthours",
            },
            {
                "period": "2023-01-01T09",
                "respondent": "AECI",
                "respondent-name": "Associated Electric Cooperative, Inc.",
                "fueltype": "COL",
                "type-name": "Coal",
                "value": 1645,
                "value-units": "megawatthours",
            },
            {
                "period": "2023-01-01T10",
                "respondent": "AECI",
                "respondent-name": "Associated Electric Cooperative, Inc.",
                "fueltype": "COL",
                "type-name": "Coal",
                "value": 1658,
                "value-units": "megawatthours",
            },
            {
                "period": "2023-01-01T11",
                "respondent": "AECI",
                "respondent-name": "Associated Electric Cooperative, Inc.",
                "fueltype": "COL",
                "type-name": "Coal",
                "value": 1663,
                "value-units": "megawatthours",
            },
            {
                "period": "2023-01-01T12",
                "respondent": "AECI",
                "respondent-name": "Associated Electric Cooperative, Inc.",
                "fueltype": "COL",
                "type-name": "Coal",
                "value": 1669,
                "value-units": "megawatthours",
            },
            {
                "period": "2023-01-01T13",
                "respondent": "AECI",
                "respondent-name": "Associated Electric Cooperative, Inc.",
                "fueltype": "COL",
                "type-name": "Coal",
                "value": 1673,
                "value-units": "megawatthours",
            },
            {
                "period": "2023-01-01T14",
                "respondent": "AECI",
                "respondent-name": "Associated Electric Cooperative, Inc.",
                "fueltype": "COL",
                "type-name": "Coal",
                "value": 1661,
                "value-units": "megawatthours",
            },
            {
                "period": "2023-01-01T15",
                "respondent": "AECI",
                "respondent-name": "Associated Electric Cooperative, Inc.",
                "fueltype": "COL",
                "type-name": "Coal",
                "value": 1459,
                "value-units": "megawatthours",
            },
        ],
        "description": "Hourly net generation by balancing authority and energy source.  \n    Source: Form EIA-930\n    Product: Hourly Electric Grid Monitor",
    },
    "request": {
        "command": "/v2/electricity/rto/fuel-type-data/data/",
        "params": {
            "facets": {"respondent": ["AECI"], "fueltype": ["COL"]},
            "start": "2023-01-01T00",
            "sort": [{"column": "period", "direction": "asc"}],
            "data": ["value"],
            "length": 16,
            "end": "2023-01-01T23",
            "offset": 0,
            "api_key": "29fcc837601c99796760ab0b626708c5",
        },
    },
    "apiVersion": "2.1.4",
}

RETURN_VALUE_2 = {
    "response": {
        "warnings": [
            {
                "warning": "incomplete return",
                "description": "The API can only return 5000 rows in JSON format.  Please consider constraining your request with facet, start, or end, or using offset to paginate results.",
            }
        ],
        "total": 24,
        "dateFormat": 'YYYY-MM-DD"T"HH24',
        "frequency": "hourly",
        "data": [
            {
                "period": "2023-01-01T16",
                "respondent": "AECI",
                "respondent-name": "Associated Electric Cooperative, Inc.",
                "fueltype": "COL",
                "type-name": "Coal",
                "value": 1286,
                "value-units": "megawatthours",
            },
            {
                "period": "2023-01-01T17",
                "respondent": "AECI",
                "respondent-name": "Associated Electric Cooperative, Inc.",
                "fueltype": "COL",
                "type-name": "Coal",
                "value": 1234,
                "value-units": "megawatthours",
            },
            {
                "period": "2023-01-01T18",
                "respondent": "AECI",
                "respondent-name": "Associated Electric Cooperative, Inc.",
                "fueltype": "COL",
                "type-name": "Coal",
                "value": 1384,
                "value-units": "megawatthours",
            },
            {
                "period": "2023-01-01T19",
                "respondent": "AECI",
                "respondent-name": "Associated Electric Cooperative, Inc.",
                "fueltype": "COL",
                "type-name": "Coal",
                "value": 1473,
                "value-units": "megawatthours",
            },
            {
                "period": "2023-01-01T20",
                "respondent": "AECI",
                "respondent-name": "Associated Electric Cooperative, Inc.",
                "fueltype": "COL",
                "type-name": "Coal",
                "value": 1505,
                "value-units": "megawatthours",
            },
            {
                "period": "2023-01-01T21",
                "respondent": "AECI",
                "respondent-name": "Associated Electric Cooperative, Inc.",
                "fueltype": "COL",
                "type-name": "Coal",
                "value": 1481,
                "value-units": "megawatthours",
            },
            {
                "period": "2023-01-01T22",
                "respondent": "AECI",
                "respondent-name": "Associated Electric Cooperative, Inc.",
                "fueltype": "COL",
                "type-name": "Coal",
                "value": 1524,
                "value-units": "megawatthours",
            },
            {
                "period": "2023-01-01T23",
                "respondent": "AECI",
                "respondent-name": "Associated Electric Cooperative, Inc.",
                "fueltype": "COL",
                "type-name": "Coal",
                "value": 1580,
                "value-units": "megawatthours",
            },
        ],
        "description": "Hourly net generation by balancing authority and energy source.  \n    Source: Form EIA-930\n    Product: Hourly Electric Grid Monitor",
    },
    "request": {
        "command": "/v2/electricity/rto/fuel-type-data/data/",
        "params": {
            "facets": {"respondent": ["AECI"], "fueltype": ["COL"]},
            "start": "2023-01-01T00",
            "sort": [{"column": "period", "direction": "asc"}],
            "data": ["value"],
            "length": 16,
            "end": "2023-01-01T23",
            "offset": 16,
            "api_key": "29fcc837601c99796760ab0b626708c5",
        },
    },
    "apiVersion": "2.1.4",
}
